<a href="https://colab.research.google.com/github/vashishthaaman2-ship-it/Sales-analysis-with-ms-excel/blob/main/Data_reviewing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
path='/content/sample_data/california_housing_train.csv'
df= pd.read_csv(path)
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [ ]:
#select colums
df[['population','latitude']]

       population  latitude
0          1015.0     34.19
1          1129.0     34.40
2           333.0     33.69
3           515.0     33.64
4           624.0     33.57
...           ...       ...
16995       907.0     40.58
16996      1194.0     40.69
16997      1244.0     41.84
16998      1298.0     41.80
16999       806.0     40.54

[17000 rows x 2 columns]

In [ ]:
#select rows multiple and single

df.loc[(df.housing_median_age == 15.0) &
       (df.population >= 1015.0)]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
38,-115.48,32.68,15.0,3414.0,666.0,2097.0,622.0,2.3319,91200.0
79,-115.56,32.80,15.0,1171.0,328.0,1024.0,298.0,1.3882,69400.0
133,-116.06,34.15,15.0,10377.0,2331.0,4507.0,1807.0,2.2466,66800.0
179,-116.31,33.67,15.0,2214.0,410.0,1152.0,350.0,2.9187,93400.0
...,...,...,...,...,...,...,...,...,...
16598,-122.71,38.50,15.0,5645.0,830.0,2324.0,769.0,6.6104,330900.0
16638,-122.73,38.43,15.0,3265.0,690.0,1629.0,629.0,3.7132,167600.0
16836,-123.34,39.50,15.0,2342.0,535.0,1064.0,433.0,1.8967,96600.0
16957,-124.16,41.74,15.0,2715.0,569.0,1532.0,530.0,2.1829,69500.0
16983,-124.19,41.78,15.0,3140.0,714.0,1645.0,640.0,1.6654,74600.0

In [ ]:
#iloc index value based on
df.iloc[15]

longitude              -114.6500
latitude                 34.8900
housing_median_age       17.0000
total_rooms            2556.0000
total_bedrooms          587.0000
population             1005.0000
households              401.0000
median_income             1.6991
median_house_value    69100.0000
Name: 15, dtype: float64

In [ ]:
df.iloc[15:100]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
15,-114.65,34.89,17.0,2556.0,587.0,1005.0,401.0,1.6991,69100.0
16,-114.65,33.60,28.0,1678.0,322.0,666.0,256.0,2.9653,94900.0
17,-114.65,32.79,21.0,44.0,33.0,64.0,27.0,0.8571,25000.0
18,-114.66,32.74,17.0,1388.0,386.0,775.0,320.0,1.2049,44000.0
19,-114.67,33.92,17.0,97.0,24.0,29.0,15.0,1.2656,27500.0
...,...,...,...,...,...,...,...,...,...
95,-115.58,32.81,5.0,805.0,143.0,458.0,143.0,4.4750,96300.0
96,-115.58,32.81,10.0,1088.0,203.0,533.0,201.0,3.6597,87500.0
97,-115.58,32.79,14.0,1687.0,507.0,762.0,451.0,1.6635,64400.0
98,-115.58,32.78,5.0,2494.0,414.0,1416.0,421.0,5.7843,110100.0
99,-115.59,32.85,20.0,1608.0,274.0,862.0,248.0,4.8750,90800.0

In [ ]:
d['hof using_median_age'] > 20.0

0        False
1        False
2        False
3        False
4        False
         ...
16995     True
16996     True
16997    False
16998    False
16999     True
Name: housing_median_age, Length: 17000, dtype: bool

In [ ]:
df[df['housing_median_age'] > 20.0]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
5,-114.58,33.63,29.0,1387.0,236.0,671.0,239.0,3.3438,74000.0
6,-114.58,33.61,25.0,2907.0,680.0,1841.0,633.0,2.6768,82400.0
7,-114.59,34.83,41.0,812.0,168.0,375.0,158.0,1.7083,48500.0
8,-114.59,33.61,34.0,4789.0,1175.0,3134.0,1056.0,2.1782,58400.0
9,-114.60,34.83,46.0,1497.0,309.0,787.0,271.0,2.1908,48100.0
...,...,...,...,...,...,...,...,...,...
16993,-124.23,40.54,52.0,2694.0,453.0,1152.0,435.0,3.0806,106700.0
16994,-124.25,40.28,32.0,1430.0,419.0,434.0,187.0,1.9417,76100.0
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [ ]:
#save the outcome data
df_filter=  df[df['housing_median_age'] > 20.0]

In [ ]:
df_filter

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
5,-114.58,33.63,29.0,1387.0,236.0,671.0,239.0,3.3438,74000.0
6,-114.58,33.61,25.0,2907.0,680.0,1841.0,633.0,2.6768,82400.0
7,-114.59,34.83,41.0,812.0,168.0,375.0,158.0,1.7083,48500.0
8,-114.59,33.61,34.0,4789.0,1175.0,3134.0,1056.0,2.1782,58400.0
9,-114.60,34.83,46.0,1497.0,309.0,787.0,271.0,2.1908,48100.0
...,...,...,...,...,...,...,...,...,...
16993,-124.23,40.54,52.0,2694.0,453.0,1152.0,435.0,3.0806,106700.0
16994,-124.25,40.28,32.0,1430.0,419.0,434.0,187.0,1.9417,76100.0
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [ ]:
#select multiple values

df[
    (df['housing_median_age'] > 20.0) &
    (df['latitude'] >= 40.28)
]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
10315,-120.08,41.79,34.0,1355.0,262.0,434.0,178.0,2.0903,56100.0
10348,-120.12,41.40,33.0,2820.0,515.0,976.0,403.0,2.6062,52600.0
10450,-120.35,40.63,33.0,240.0,49.0,63.0,22.0,3.6250,200000.0
10470,-120.38,40.98,27.0,777.0,185.0,318.0,115.0,1.6833,40000.0
10504,-120.42,40.38,26.0,1652.0,313.0,762.0,280.0,2.4757,85600.0
...,...,...,...,...,...,...,...,...,...
16993,-124.23,40.54,52.0,2694.0,453.0,1152.0,435.0,3.0806,106700.0
16994,-124.25,40.28,32.0,1430.0,419.0,434.0,187.0,1.9417,76100.0
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0